# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d09d408e3bdaf29aa3b3794dcd9b5c17"
application_url = "https://faced-methods-studies-nonprofit.trycloudflare.com"
embedded = true
name = "Remix First App"
handle = "remix-first-app-2"

[build]
include_config_on_deploy = true
dev_store_url = "shop-dummy2.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://faced-methods-studies-nonprofit.trycloudflare.com/auth/callback", "https://faced-methods-studies-nonprofit.trycloudflare.com/auth/shopify/callback", "https://faced-methods-studies-nonprofit.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
